syntax = "proto3";

// Unified error handling
enum ErrorCode {
  ERROR_CODE_UNSPECIFIED = 0;
  ERROR_CODE_INVALID_ARGUMENT = 1;
}
message ErrorDetails {
  ErrorCode code = 1;
  string message = 2;
}

message StandardResponse {
  bool ok = 1;
  string message = 2;
  ErrorDetails error = 3;
}

message DaemonStartRequest {}
message DaemonStartResponse {
  StandardResponse stdrp = 1;
}

message DaemonStopRequest {}
message DaemonStopResponse {
  StandardResponse stdrp = 1;
}

message DaemonStatusRequest {}
message DaemonStatusResponse {
  StandardResponse stdrp = 1;
  bool running = 2;
  optional int32 pid = 3;
}

message StartInstrumentRequest {
  string config_path = 1;
  optional string plugin_path = 2;
  optional string log_level = 3;
}
message StartInstrumentResponse {
  StandardResponse stdrp = 1;
}

message StopInstrumentRequest {
  string instrument_name = 1;
}
message StopInstrumentResponse {
  StandardResponse stdrp = 1;
}

message InstrumentStatusRequest {
  string instrument_name = 1;
}
message InstrumentStats {
  string commands_sent = 1;
  string commands_completed = 2;
  string commands_failed = 3;
  string commands_timeout = 4;
}
message InstrumentStatusResponse {
  StandardResponse stdrp = 1;
  optional InstrumentStats stats = 3;
}

message ListInstrumentsRequest {}
message ListInstrumentsResponse {
  StandardResponse stdrp = 1;
  repeated string instrument_name = 2;
}

enum LuaTypes {
  LUA_TYPES_UNSPECIFIED = 0;
  LUA_TYPES_INT64_T = 1;
  LUA_TYPES_DOUBLE = 2;
  LUA_TYPES_BOOL = 3;
  // All of these are stored in the string VariableValue
  LUA_TYPES_STRING = 4;
  LUA_TYPES_DATA_BUFFER = 5;
  LUA_TYPES_CALL_STACK = 6;
}
message Parameter {
  string name = 1;
  optional LuaTypes type = 2;
}
message TypeManifest {
  repeated Parameter parameters = 1;
}
message VariableValue {
  oneof value {
    int64 i = 1;
    double d = 2;
    bool b = 3;
    string s = 4;
  }
}
message GlobalVariables {
  map<string, VariableValue> values = 1;
}
message MeasureRequest {
  string script_path = 1;
  GlobalVariables globals = 2;
  bool block_inject_globals = 3;
  optional TypeManifest type_manifest = 4;
  optional int32 context_schema_version = 5;
}
message DataBufferMetadata {
  int32 element_count = 1;
  int32 inst_data_type = 2; // INST_DATA_<...>
}
message TypedParameter {
  string name = 1;
  LuaTypes type = 2;
  VariableValue value = 3;
  optional DataBufferMetadata dbmeta = 4; // Additional metadata for DataBuffer
}
message CommandResult {
  string instrument_name = 1;
  string verb = 2;
  int64 executed_at_ms = 3;
  repeated TypedParameter return = 4;
}
message MeasureResponse {
  StandardResponse stdrp = 1;
  repeated CommandResult results = 2;
}
