if(EXISTS "/home/tylerk/falcon-dev/instrument-script-server/build-win/tests/integration_tests[1]_tests.cmake")
  include("/home/tylerk/falcon-dev/instrument-script-server/build-win/tests/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
