name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # Build and test for Linux (runs on all pushes and tags)
  linux-build:
    uses: ./.github/workflows/linux-ci.yml
    permissions:
      contents: read

  # Build and test for Windows (runs on all pushes and tags)
  windows-build:
    uses: ./.github/workflows/windows-ci.yml
    permissions:
      contents: read
